### ISSUE TITLE
incomplete results 

### ISSUE THREAD

**Issue by MrKevinDC** [ridgelab/JustOrthologs#10]
Hi, I was running `JustOrthologs` with NCBI-sourced fastas and gffs of species [_homo sapiens_](https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/latest_assembly_versions/GCF_000001405.39_GRCh38.p13/) and [_pan paniscus_](https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Pan_paniscus/latest_assembly_versions/GCF_013052645.1_Mhudiblu_PPA_v0/), the same as the sample data, and I am only finding 38 ortholog groups. 

The commands I have executed are:

`['python', 'gff3_parser.py', '-g', 'GCF_013052645.1_Mhudiblu_PPA_v0_genomic.gff.gz', '-f', 'GCF_013052645.1_Mhudiblu_PPA_v0_genomic.fna.gz', '-o', 'pan_paniscus.fasta'`]
`
['python', 'gff3_parser.py', '-g', 'GCF_000001405.39_GRCh38.p13_genomic.gff.gz', '-f', 'GCF_000001405.39_GRCh38.p13_genomic.fna.gz', '-o', 'homo_sapiens.fasta']`

And finally:

`['python', 'JustOrthologs/justOrthologs.py', '-q', 'pan_paniscus.fasta', '-s', 'homo_sapiens.fasta', '-o', 'output', '-t', '15', '-c']`

Any ideas why so few orthologs were found?

**Comment by miller34** [comment]
Hello @MrKevinDC,
Thank you for your interest in `JustOrthologs`. 
The main issue is that you need to sort the output from `gff3_parser.py` before it is used by `JustOrthologs.py`. There are two options to resolve the issue:

1. Instead of calling `gff3_parser.py` directly, you can use `wrapper.py`, which will call all of the necessary preparation scripts to ensure that `JustOrthologs` is called without issue. I just downloaded the files that you specified and successfully ran the script with the following command (user time 256 minutes; real time 19 minutes):

`python2 wrapper.py -g1 GCF_000001405.39_GRCh38.p13_genomic.gff.gz -g2 GCF_013052645.1_Mhudiblu_PPA_v0_genomic.gff.gz  -r1 GCF_000001405.39_GRCh38.p13_genomic.fna.gz -r2 GCF_013052645.1_Mhudiblu_PPA_v0_genomic.fna  -all -o output`

My output file found 16,949 orthologs.

2. If you want to manually call the intermediate scripts, you need to call `sortFastaBySeqLen.sh` after `gff3_parser.py`.  `sortFastaBySeqLen.sh` sorts the CDS fasta file created by `gff3_parser.py` by the number of CDS regions. For example, the first sequence will have 1 CDS region (i.e., no splicing), and the last sequence will have the maximum number of CDS regions (i.e., most splicing). More information about that script can be found in `README_OTHER_PROGRAMS`, if desired.

Hope that resolves the issue for you!

**Comment by MrKevinDC** [comment]
Thank you very much for your quick response and for running the test yourself @miller34 , it is extremely helpful to know what to expect, a big thanks from me and my team.
