### ISSUE TITLE
Multiple species

### ISSUE THREAD

**Issue by ardy20** [ridgelab/JustOrthologs#12]
Hello

Could you please help me to run your pipeline? I only have one gene that I would like to find its orthologs in 136 sequenced plant genomes.

Do I need to download the sequenced genomes (in a folder) or this tool works with databases?

Does this tool need MySql?

Please give me an example script as well.

Regards

**Comment by miller34** [comment]
Hello! 
JustOrthologs does not require MySQL or use databases. You will need to have the CDS regions annotated, which means that you'll need the GFF3 and FASTA file for your ortholog and the 136 other species. The README_WRAPPER shows how to run an example script, and test file paths are also located in the README_WRAPPER. Since you're analyzing 1 vs 136, you might want to do something similar to what's done in README_RUN_MULTIPLE_SPECIES, which looks at identifying ortholog clusters between multiple species. Or you can run pairwise comparisons of JustOrthologs for your gene versus species 1 followed by species 2, etc. The example files and the READMEs in the git repo should help you see what file formats you need.
