### ISSUE TITLE
using JustOrthologs with transcriptome data?

### ISSUE THREAD

**Issue by spflanagan** [ridgelab/JustOrthologs#5]
Hello,
I'm analyzing transcriptome data from 4 species (without genomes) and would like to identify orthologs across the transcriptomes. Reading the paper and documentation, it seems to me that JustOrthologs should work with transcriptome data. However, when I run JustOrthologs on my transcriptomes (using the longest ORFs from the de novo assemblies), I end up with essentially no orthologs identified, even when changing the correlation value.

Is it possible to use JustOrthologs on transcriptome datasets, and if so, can you provide advice for using your tool with these types of data?

Thank you in advance,
Sarah

**Comment by ridgelab** [comment]
Hello Sarah,
Thank you for your interest in JustOrthologs. We are actively developing a second version of JustOrthologs that will make transcriptomic analyses easier. Currently, JustOrthologs requires CDS regions to be identified for each gene. More CDS regions per gene increases the precision and accuracy of JustOrthologs. Also, comparisons of closely related species (vs distantly related species) will increase the accuracy of JustOrthologs. From my experience, most transcriptome data do not have the annotated splice sites necessary for JustOrthologs to identify most orthologs. As an example, the following would be needed for the full utility of JustOrthologs:
>gene 1 CDS 1
ATGAAATTTAAA
>gene 1 CDS 2
CGCGGGCGG
>gene 1 CDS 3
TTTCCCGCGTAA
>gene 2 CDS 1
ATGTTTGGGCCCTTT
>gene 2 CDS 2
GGGTTTTGA
...

If you're looking at only the longest ORF, JustOrthologs will likely miss most orthologs because it compares individual CDS regions within each gene.
Best,
Justin
